# Generated by Django 3.0.5 on 2020-12-17 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Registration',
            fields=[
                ('reg_id', models.AutoField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=200)),
                ('last_name', models.CharField(max_length=200)),
                ('title', models.CharField(max_length=100)),
                ('parent_id', models.IntegerField()),
                ('points', models.IntegerField(blank=True, null=True)),
            ],
        ),
    ]
