# Generated by Django 3.0.5 on 2020-12-17 12:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_auto_20201217_1528'),
    ]

    operations = [
        migrations.RenameField(
            model_name='registration',
            old_name='boss',
            new_name='Boss',
        ),
        migrations.AlterField(
            model_name='registration',
            name='points',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='registration',
            name='title',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Title'),
        ),
    ]
