# Generated by Django 3.0.5 on 2020-12-17 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_auto_20201217_2118'),
    ]

    operations = [
        migrations.RenameField(
            model_name='registration',
            old_name='Boss',
            new_name='boss',
        ),
        migrations.AlterField(
            model_name='registration',
            name='title',
            field=models.CharField(max_length=200),
        ),
    ]
