# Generated by Django 3.0.5 on 2020-12-20 04:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_auto_20201217_2245'),
    ]

    operations = [
        migrations.AddField(
            model_name='registration',
            name='child',
            field=models.TextField(blank=True, null=True),
        ),
    ]
